config/routes.rb
Foo::Application.routes.draw do
  resources :prefectures

end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController

  def index

    @prefectures = Prefecture.all
    respond_to do |format|
      format.html # index.html.erb
#      format.json { render json: @prefectures }
    end
#    @prefectures = {id: params[:id],title: "aaa",content: "bbbbb"}
#    respond_to do |format|
#      format.json { render json: @prefectures,callback: params[:callback] }
#    end
    require 'net/http'
    Net::HTTP.version_1_2

 #   req = Net::HTTP::GET.new("/rest/photo_album") 
  end

  # GET /prefectures/1
  # GET /prefectures/1.json
  def show
    @prefecture = Prefecture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prefecture }
    end
  end

  # GET /prefectures/new
  # GET /prefectures/new.json
  def new
    @prefecture = Prefecture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prefecture }
    end
  end

  # GET /prefectures/1/edit
  def edit
    @prefecture = Prefecture.find(params[:id])
  end

  # POST /prefectures
  # POST /prefectures.json
  def create
    @prefecture = Prefecture.new(params[:prefecture])

    respond_to do |format|
      if @prefecture.save
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully created.' }
        format.json { render json: @prefecture, status: :created, location: @prefecture }
      else
        format.html { render action: "new" }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prefectures/1
  # PUT /prefectures/1.json
  def update
    @prefecture = Prefecture.find(params[:id])

    respond_to do |format|
      if @prefecture.update_attributes(params[:prefecture])
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prefectures/1
  # DELETE /prefectures/1.json
  def destroy
    @prefecture = Prefecture.find(params[:id])
    @prefecture.destroy

    respond_to do |format|
      format.html { redirect_to prefectures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prefectures/_form.html.erb
<%= form_for(@prefecture) do |f| %>
  <% if @prefecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prefecture.errors.count, "error") %> prohibited this prefecture from being saved:</h2>

      <ul>
      <% @prefecture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prefectures/edit.html.erb
<h1>Editing prefecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @prefecture %> |
<%= link_to 'Back', prefectures_path %>

app/views/prefectures/index.html.erb
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="../citylist.json"></script>
<h1>Listing prefectures</h1>

<table>
  <select name="prefecture">
    <% @prefectures.each do |pref| %>
      <option value="<%= pref.id %>"><%= pref.name %></option>
    <% end %>
  </select>

  <span id="city"></span>

  <% @prefectures.each do |prefecture| %>
    <tr>
      <td><%= prefecture.name %></td>
      <td><%= link_to 'Show', prefecture %></td>
      <td><%= link_to 'Edit', edit_prefecture_path(prefecture) %></td>
      <td><%= link_to 'Destroy', prefecture, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>

</table>

<br />

<%= link_to 'New Prefecture', new_prefecture_path %>

app/views/prefectures/new.html.erb
<h1>New prefecture</h1>

<%= render 'form' %>

<%= link_to 'Back', prefectures_path %>

app/views/prefectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @prefecture.name %>
</p>


<%= link_to 'Edit', edit_prefecture_path(@prefecture) %> |
<%= link_to 'Back', prefectures_path %>